### PR TITLE
Adding download page along with the pointers for 0.1.0 release

### PR DESCRIPTION
**Pull request by snleee**
screen shot 2019-03-07 at 5 39 21 pm

### CODE REVIEW

**Comment by snleee** [comment]
TODO: we need to separate out the navigator bar from `index.html` files so that we won't need to modify in the multiple places.

**Comment by sunithabeeram** [comment]
Going by the Screenshot, I think it would be much better if we had Downloads be below the apache incubator blurb.

**Comment by snleee** [comment]
@sunithabeeram I think that Apache Incubator blurb is the footer?

**Review by sunithabeeram — APPROVED** [review]
We can iterate over the look and feel if needed later.

**Pull request merged**
